apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexusops-frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zulkuf15/nexusops-manifests.git
    targetRevision: HEAD
    path: nexusops-frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nexusops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true